name: igl-website-devcontainer

services:
  devcontainer:
    build: .
    environment:
      # Tell sops where to find the secret key for age decryption.
      SOPS_AGE_KEY_FILE: /workspace/age-secret-key.txt
    volumes:
      - ..:/workspace:cached
      - $HOME/.kube:/root/.kube
