# SETUP:
#
# Create a .env file with:
#
# - ADMIN_USER
# - POSTGRES_DB
# - POSTGRES_PASSWORD
# - POSTGRES_USER
# - SMTP_PASSWORD
# - SMTP_USER

configs:
  grafana:
    file: ./grafana.ini

networks:
  traefik_default:
    external: true
  vmagent_default:
    external: true

services:
  grafana:
    cap_drop:
      - ALL
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    image: docker.io/grafana/grafana:11.5.2@sha256:8b37a2f028f164ce7b9889e1765b9d6ee23fec80f871d156fbf436d6198d32b7
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.rule: Host(`grafana.zarantonello.net`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      victoriametrics.job: grafana
      victoriametrics.port: 3000
    networks:
      - default
      - traefik_default
      - vmagent_default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 31904:31904
    volumes:
      - ./provisioning:/etc/grafana/provisioning:z
      - data:/var/lib/grafana

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: docker.io/library/postgres:17.4-alpine@sha256:c4c3cded22488238ed0df51b82913b5d3b426fad19fbe205a711f05f5dba5c45
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=70,gid=70
      - /var/run/postgresql:uid=70,gid=70
    # User has to be 70, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 70:70
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  data: {}
  postgres: {}
